services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
    environment:
      - BACKEND_URL=https://api.open-elements.cloud
    depends_on:
      backend:
        condition: service_healthy
