version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "9081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build: ./frontend
    ports:
      - "4000:3000"
    environment:
      BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - backend

