name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "corretto"
      - run: |
          cd backend
          ./mvnw clean verify

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: |
          pnpm install --no-frozen-lockfile
          pnpm run build
          pnpm test -- --passWithNoTests

  artifacts:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: backend-jar
          path: backend/target/*.jar
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/.next/
